# Generated by Django 5.0.7 on 2024-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
     migrations.CreateModel(
         name='Classes',
         fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seat', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('name_of_teachers', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=0)),
                ('school_year', models.IntegerField()),

    
         ],
     ),
         migrations.DeleteModel(
             name='Class',
         ),
         
     
    ]
