# Generated by Django 5.0.7 on 2024-07-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_description_of_course_class_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='school_year',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
