# Generated by Django 5.0.7 on 2024-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='school_year',
            field=models.IntegerField(),
        ),
    ]
