# Generated by Django 5.0.7 on 2024-08-14 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seat', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('name_of_teachers', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=0)),
                ('school_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('Nationality', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=6)),
                ('level_of_education', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('id_number', models.IntegerField()),
                ('bio', models.TextField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='classperiod.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classperiod.classes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classperiod.teacher')),
            ],
        ),
    ]
