# Generated by Django 5.0.7 on 2024-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.IntegerField()),
                ('number_of_courses', models.IntegerField()),
                ('name_of_teachers', models.CharField(max_length=30)),
                ('course_prestiquies', models.TextField(blank=True, null=True)),
                ('description_of_course', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
